#!name=Lightroom Premium
#!desc=Mở khóa tính năng Premium cho Adobe Lightroom
#!author=quocchienn (trích xuất từ Shadowrocket )

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Script]
Lightroom = type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v\d\/accounts,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/QuocChienn2709/quocchiennshadowrocket/refs/heads/main/lightroom.js,script-update-interval=-1

[MITM]
hostname = photos.adobe.io
enable = true
