#!name=PicsArt Crack
#!desc=Kích hoạt Premium cho PicsArt (chỉ dành cho PicsArt)
#!author=quocchienn (trích xuất từ Shadowrocket )
[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Script]
PicsArt = type=http-request,pattern=^https:\/\/api\.picsart\.com\/gw-v2\/shop\/subscription\/apple\/purchases,script-path= https://raw.githubusercontent.com/QuocChienn2709/quocchiennshadowrocket/refs/heads/main/PicsArt.js,requires-body=true,timeout=60
PicsArtStorages = type=http-request,pattern=^https:\/\/api\.picsart\.com\/gw-v2\/cloud-storage\/v1\/me\/storages,script-path=https://github.com/QuocChienn2709/quocchiennshadowrocket/raw/refs/heads/main/PicsArtStorages.js,requires-body=true,timeout=60

[MITM]
hostname = api.picsart.com
enable = true
